name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. repo clone
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. install dependencies
      - name: Install dependencies
        run: npm install

      # 4. run lint
      - name: Run Lint
        run: npm run lint

      # 5. run tests
      - name: Run Tests
        run: npm run test

      # 6. build project
      - name: Build Project
        run: npm run build